version: 0.0
os: linux
files:
  - source: /
    destination: /new_chatapp
hooks: 
  ApplicationStop:
    - location: /stopserver.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: /installdependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /change_file.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /startserver.sh
      timeout: 300
      runas: root
