version: 0.0
os: linux
files:
  - source: /
    destination: /new_chatapp
    overwrite: true
hooks: 
  ApplicationStop:
    - location: /stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: /install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /change_file.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /start_server.sh
      timeout: 300
      runas: root
